import {LegalPage,LegalSection} from "../../../components/legal-page";
import {LEGAL_VERSIONS} from "../../../lib/legal-versions";
export const metadata={title:"Security — StudioTasker"};
export default function Security(){
 return <LegalPage title="Security" kicker="TRUST / TECHNICAL & ORGANISATIONAL MEASURES" version={LEGAL_VERSIONS.security}>
  <LegalSection title="Security model"><p>StudioTasker uses layered controls designed for a multi-tenant studio-management SaaS. Security measures are reviewed as the service evolves and are intended to support confidentiality, integrity, availability and tenant separation.</p></LegalSection>
  <LegalSection title="Access and authentication"><ul><li>Role-based studio access for owner, manager, instructor and receptionist roles.</li><li>Server-side membership checks before tenant-scoped operations.</li><li>HTTP-only session cookies with secure transport requirements in production.</li><li>Email verification and controlled password-reset challenges.</li><li>One-way password hashing; plaintext passwords are not stored.</li></ul></LegalSection>
  <LegalSection title="Tenant and database isolation"><ul><li>Studio records carry a tenant/studio identifier.</li><li>PostgreSQL Row Level Security is forced for tenant-scoped tables covered by the application design.</li><li>The runtime database role is tested to ensure it is not a superuser and cannot bypass RLS.</li><li>Cross-tenant reads and writes are covered by automated integration tests.</li></ul></LegalSection>
  <LegalSection title="Transport and infrastructure"><ul><li>Commercial registration requires an HTTPS application origin.</li><li>Application secrets and provider credentials are environment configuration, not committed to the repository.</li><li>Database connections can require certificate-validated TLS where the production provider supports it.</li><li>Payment-card data for the StudioTasker subscription is handled by the external billing provider rather than stored in StudioTasker’s application database.</li></ul></LegalSection>
  <LegalSection title="Backups and recovery"><ul><li>Commercial registration is fail-closed unless backup configuration is present.</li><li>Backup tooling uses encrypted backup artefacts and verification/restore workflows.</li><li>Customers should still maintain exports of records they independently need for statutory or business-retention purposes.</li></ul></LegalSection>
  <LegalSection title="Application controls"><ul><li>Same-origin checks protect sensitive write requests.</li><li>Input validation and constrained enums/ranges are applied to core settings and operations.</li><li>Audit-oriented records exist for selected export, credit-correction, attendance and legal-acceptance events.</li><li>Automated build/regression tests cover authentication, tenant isolation, mobile/accessibility guards, billing gates, backups and live HTTP behaviour.</li></ul></LegalSection>
  <LegalSection title="Customer responsibilities"><p>Security is shared. Customers should use unique passwords, protect mailbox access, assign the least privilege needed, remove former staff promptly and avoid entering sensitive data the service is not designed to store.</p></LegalSection>
  <LegalSection title="Reporting a concern"><p>If you believe you have found a security issue, use the legal/security contact shown below and provide enough information to reproduce the issue without accessing data that does not belong to you.</p></LegalSection>
 </LegalPage>
}
