import Link from "next/link";
import {LegalPage,LegalSection} from "../../../components/legal-page";
import {LEGAL_VERSIONS} from "../../../lib/legal-versions";
import {legalOperator} from "../../../lib/server/legal-config";
export const metadata={title:"Data Processing Agreement | StudioTasker"};
export default function DPA(){
 const op=legalOperator();
 return <LegalPage title="Data Processing Agreement" kicker="GDPR / CONTROLLER–PROCESSOR TERMS" version={LEGAL_VERSIONS.dpa}>
  <LegalSection title="1. Scope and parties"><p>This Data Processing Agreement (“DPA”) forms part of the StudioTasker Terms of Service between Customer and the <strong>independent individual operator of StudioTasker</strong>. {op.configured&&<>The legal operator is <strong>{op.name}</strong>.</>} It applies only where StudioTasker processes personal data on Customer’s behalf in connection with the StudioTasker service.</p><p>For that processing, Customer is the controller (or a processor acting for another controller, where applicable) and StudioTasker is the processor, unless applicable law requires a different classification for a specific activity.</p><p><strong>Excluded from this processor DPA:</strong> buyer/payment data independently processed by Paddle as StudioTasker’s authorised reseller and Merchant of Record. Paddle and StudioTasker act as independent controllers for their respective checkout/payment purposes under the applicable Paddle–supplier data-sharing terms.</p></LegalSection>
  <LegalSection title="2. Customer instructions"><p>StudioTasker will process Customer Personal Data only on documented instructions from Customer, including the instructions embodied in the Terms, Customer’s configuration and ordinary use of the service, unless law requires otherwise. If legally permitted, StudioTasker will inform Customer before processing required solely by law.</p></LegalSection>
  <LegalSection title="3. Processing details"><table className="lg-table"><tbody>
   <tr><th>Subject matter</th><td>Hosting and operating studio-management software and related support/security functions.</td></tr>
   <tr><th>Duration</th><td>For the subscription term and a post-termination period appropriate to verified export/deletion requests, applicable law and documented backup rotation. No automatic erasure date is presently guaranteed.</td></tr>
   <tr><th>Nature and purpose</th><td>Storage, organisation, retrieval, display, scheduling, booking administration, attendance, internal credit/package tracking, follow-up tasks, exports, backups and security monitoring.</td></tr>
   <tr><th>Data subjects</th><td>Customer staff, leads, members/clients/students and other contacts entered by Customer.</td></tr>
   <tr><th>Data categories</th><td>Names, contact details, relationship/status information, booking/class history, attendance, internal credit/package status, notes and workspace identifiers.</td></tr>
   <tr><th>Special-category data</th><td>Not intended or authorised by default. Customer must not submit health, biometric, criminal-offence or comparable sensitive data unless separately agreed in writing and supported by appropriate safeguards.</td></tr>
  </tbody></table></LegalSection>
  <LegalSection title="4. Confidentiality"><p>StudioTasker will ensure that persons authorised to process Customer Personal Data are bound by appropriate confidentiality obligations and access it only as needed for their role.</p></LegalSection>
  <LegalSection title="5. Security"><p>StudioTasker will implement appropriate technical and organisational measures taking into account the nature of processing and risk. Current measures are described in <Link href="/legal/security">Security</Link> and include tenant isolation, restricted database access, secure sessions, production HTTPS requirements, access controls, backup tooling that requires deployment-specific verification, and security-oriented logging. These descriptions are not evidence of a completed production restore drill or 24/7 monitoring.</p></LegalSection>
  <LegalSection title="6. Subprocessors"><p>Customer grants general written authorisation for StudioTasker to use subprocessors necessary to provide the service, subject to data-protection obligations no less protective than required by applicable law. The current list is maintained at <Link href="/legal/subprocessors">Subprocessors</Link>. Where required by law, StudioTasker will provide notice of material new subprocessors and a reasonable opportunity to object on legitimate data-protection grounds.</p></LegalSection>
  <LegalSection title="7. Data-subject requests"><p>Taking into account the nature of processing, StudioTasker will provide reasonable assistance to Customer with requests to exercise rights under applicable data-protection law. StudioTasker will not independently respond to a studio member’s request concerning Customer-controlled data except as legally required or authorised by Customer.</p></LegalSection>
  <LegalSection title="8. Security incidents"><p>StudioTasker will notify Customer without undue delay after becoming aware of a personal-data breach affecting Customer Personal Data and will provide information reasonably available to assist Customer with its notification and risk-assessment obligations. Notification does not constitute an admission of fault or liability.</p></LegalSection>
  <LegalSection title="9. DPIAs and regulatory assistance"><p>Taking into account the nature of processing and information available to it, StudioTasker will provide reasonable assistance with data-protection impact assessments and prior consultations where the processing through StudioTasker gives rise to such obligations.</p></LegalSection>
  <LegalSection title="10. Return and deletion"><p>Customers can export available studio records and submit an authenticated studio-closure request. Submitting a request does not itself cancel Paddle billing or delete data. The operator must verify the requester, lawful retention obligations, subscription termination, and any technical backup-erasure limitations before arranging return or deletion as required by applicable law. Customer should export required business records before account closure.</p></LegalSection>
  <LegalSection title="11. Audit information"><p>StudioTasker will make available information reasonably necessary to demonstrate compliance with processor obligations. Audits must be proportionate, protect other customers’ confidentiality and security, and should ordinarily use available documentation or independent evidence before intrusive inspection.</p></LegalSection>
  <LegalSection title="12. International transfers" id="international-transfers"><p>If Customer Personal Data is subject to a restricted international transfer, the parties will use a legally valid transfer mechanism. Where applicable, this may require the unmodified European Commission Standard Contractual Clauses adopted under Decision (EU) 2021/914, typically the controller-to-processor module when Customer is an EEA controller and StudioTasker is a processor outside the EEA.</p><p>StudioTasker is being prepared for an EU-region production hosting setup. EU hosting can reduce cross-border infrastructure exposure, but it does not by itself eliminate transfer analysis where the individual operator or authorised support access occurs from Türkiye.</p><p className="lg-note"><strong>SCC execution:</strong> acceptance of this DPA records the controller–processor contract. Where SCCs are legally required for a specific Customer, the applicable SCC transfer addendum must also be put in place without modifying the mandatory clauses.{op.email?<> Contact {op.email} if your organisation requires a signed SCC package.</>:<> A dedicated legal contact is provided before paid service activation.</>}</p></LegalSection>
  <LegalSection title="13. Processing Annex"><table className="lg-table"><tbody>
   <tr><th>Controller</th><td>Customer/studio for member, lead and staff data entered for the studio’s purposes.</td></tr>
   <tr><th>Processor</th><td>StudioTasker for Customer Personal Data processed to provide the studio-management service.</td></tr>
   <tr><th>Data subjects</th><td>Customer staff, leads, members/clients/students and other contacts entered by Customer.</td></tr>
   <tr><th>Data categories</th><td>Names, business/contact details, studio relationship/status information, class/booking/attendance history, internal package/credit status, tasks, notes and workspace identifiers.</td></tr>
   <tr><th>Purpose</th><td>CRM, scheduling, booking administration, attendance, studio-confirmed entitlements, follow-up workflows, exports, support, backup and service security.</td></tr>
   <tr><th>Duration</th><td>Subscription term plus verified closure processing, necessary backup rotation and legally required retention periods; timing is confirmed during closure review.</td></tr>
   <tr><th>Special-category data</th><td>Not intended or authorised by default; Customer must not upload it unless separately agreed in writing and technically supported.</td></tr>
   <tr><th>Subprocessors</th><td>Maintained on the public <Link href="/legal/subprocessors">Subprocessors page</Link>; Paddle checkout processing is separately classified as independent-controller processing, not a Customer Personal Data subprocessor.</td></tr>
  </tbody></table></LegalSection>
  <LegalSection title="14. Order of precedence"><p>If this DPA conflicts with the Terms on protection of Customer Personal Data, this DPA controls to the extent of the conflict. Mandatory SCC provisions, when applicable and executed, take precedence as required by those clauses.</p></LegalSection>
 </LegalPage>
}
