import Link from "next/link";
import {LegalPage,LegalSection} from "../../../components/legal-page";
import {LEGAL_VERSIONS} from "../../../lib/legal-versions";
import {legalOperator} from "../../../lib/server/legal-config";

export const metadata={title:"Türkiye Privacy Notice (KVKK) — StudioTasker"};

export default function TurkiyePrivacyNotice(){
 const op=legalOperator();
 return <LegalPage title="Türkiye Privacy Notice (KVKK)" kicker="LAW NO. 6698 / OPERATOR-CONTROLLED DATA" version={LEGAL_VERSIONS.turkiyePrivacy}>
  <LegalSection title="1. Scope and data controller"><p>This notice is provided for transparency where Türkiye&apos;s Personal Data Protection Law No. 6698 (“KVKK”) applies to personal data for which the StudioTasker operator determines the purposes and means of processing, such as account administration, direct service communications, subscription administration, security and legal/compliance records.</p><p>{op.configured?<>Data controller: <strong>{op.name}</strong>, <strong>{op.address}</strong>, {op.country}. Contact: <strong>{op.email}</strong> · <strong>{op.phone}</strong>.</>:<>Live paid registration remains disabled until the operator&apos;s full legal identity, service address, privacy email and support phone are configured and published.</>}</p><p>For member, lead or staff data entered by a customer studio for that studio&apos;s own purposes, the studio generally determines the processing purpose and StudioTasker acts as processor/service provider under the <Link href="/legal/dpa">DPA</Link>. The studio is responsible for its own notices to those individuals.</p></LegalSection>
  <LegalSection title="2. Data categories and collection method"><p>Operator-controlled data may include account/studio name, business email, role, authentication and verification records, subscription/provider identifiers, essential support/legal correspondence, session/security events and technical request metadata. The data is collected directly from account forms and communications, automatically through necessary account/security systems, and from Paddle where needed to reconcile a StudioTasker subscription. Full payment-card data is not stored in StudioTasker.</p></LegalSection>
  <LegalSection title="3. Purposes and legal grounds"><p>Where KVKK applies, core account and service processing is not based on a bundled marketing consent. Depending on the activity, processing may be necessary for establishment or performance of the service relationship, compliance with legal obligations, establishment/exercise/protection of a right, or legitimate interests that do not override the individual&apos;s fundamental rights and freedoms. Any activity that legally requires explicit consent will be presented separately from this notice before that activity is enabled.</p></LegalSection>
  <LegalSection title="4. Recipients and transfers"><p>Data may be disclosed only as needed to relevant infrastructure/transactional-email providers, Paddle for the subscription transaction in its independent Merchant-of-Record role, professional advisers or competent public authorities where legally required. Actual production processors and hosting region are disclosed on the <Link href="/legal/subprocessors">Subprocessors & Independent Controllers</Link> page.</p><p>Any transfer from Türkiye that is legally treated as an international transfer must use an applicable mechanism under KVKK Article 9 and the current implementing rules. StudioTasker does not treat EU hosting alone as sufficient legal authority for a transfer; the live-launch legal review must confirm the mechanism required for the actual provider/access model.</p></LegalSection>
  <LegalSection title="5. Retention and security"><p>Data is retained only for the periods needed for the service relationship, account/security administration, dispute handling and applicable accounting/legal duties, subject to documented deletion and backup-rotation procedures. Security measures are summarized on the <Link href="/legal/security">Security page</Link>.</p></LegalSection>
  <LegalSection title="6. KVKK Article 11 rights"><p>Where KVKK applies, individuals may exercise the rights provided by Article 11, including requesting information about whether and how their personal data is processed, learning the purpose and recipients, requesting correction or deletion where the legal conditions are met, requesting notification of qualifying corrections/deletions to recipients, objecting to an adverse result produced exclusively by automated processing where applicable, and seeking compensation where the statutory conditions are satisfied.</p><p>{op.email?<>Requests may be sent to <strong>{op.email}</strong>. Identity verification proportionate to the request may be required before personal data is disclosed or changed.</>:<>A dedicated request contact is published before paid service activation.</>}</p></LegalSection>
  <LegalSection title="7. No bundled consent"><p>This notice is an information notice. Reading or receiving it is not treated as explicit consent, and StudioTasker does not use a single bundled checkbox to obtain consent for unrelated marketing, analytics or special-category data processing. Google Analytics, Meta Pixel and behavioural advertising trackers are not enabled in the initial production configuration.</p></LegalSection>
 </LegalPage>
}
