import Link from "next/link";
import {LegalPage,LegalSection} from "../../../components/legal-page";
import {LEGAL_VERSIONS} from "../../../lib/legal-versions";
import {legalOperator} from "../../../lib/server/legal-config";
export const metadata={title:"Privacy Policy — StudioTasker"};
export default function Privacy(){
 const op=legalOperator();
 return <LegalPage title="Privacy Policy" kicker="PRIVACY / ACCOUNT & SERVICE DATA" version={LEGAL_VERSIONS.privacy}>
  <LegalSection title="1. Who this policy covers"><p>This policy explains how <strong>{op.name}</strong> (“StudioTasker”, “we”, “us”) handles personal data in connection with the StudioTasker website, studio-owner accounts, subscription administration, security and support.</p><p>When a studio uses StudioTasker to manage its own members, leads or staff, the studio generally determines why that information is processed and acts as controller. StudioTasker processes that data on the studio’s behalf under the <Link href="/legal/dpa">Data Processing Agreement</Link>.</p></LegalSection>
  <LegalSection title="2. Data we may collect"><ul><li><strong>Account data:</strong> name or studio name, business email, role, authentication and verification information.</li><li><strong>Subscription data:</strong> plan, subscription status, provider identifiers and billing metadata. StudioTasker does not store full payment-card details.</li><li><strong>Workspace data:</strong> studio settings, classes, member/lead records, bookings, attendance, credits, tasks, notes and uploaded studio logo.</li><li><strong>Technical and security data:</strong> session identifiers, IP-derived security/audit information, user agent, timestamps, error and security events.</li><li><strong>Communications:</strong> support or legal correspondence sent to us.</li></ul></LegalSection>
  <LegalSection title="3. Why we use data"><p>Depending on the context, we process data to perform our contract, comply with legal obligations, protect the service and our legitimate interests, and where required, on the basis of consent.</p><ul><li>create and secure accounts;</li><li>provide, maintain and personalise the StudioTasker workspace;</li><li>administer subscriptions and prevent billing fraud;</li><li>send verification, password-reset and essential service messages;</li><li>protect tenant isolation, investigate abuse and maintain audit evidence;</li><li>respond to support, privacy and legal requests;</li><li>meet tax, accounting, compliance and dispute-resolution obligations.</li></ul></LegalSection>
  <LegalSection title="4. Studio member data"><p>StudioTasker does not independently decide the business purpose for a studio’s member CRM, class or booking data. Customer is responsible for its own privacy notices, lawful basis, retention decisions and responses to its members. StudioTasker processes such data only to provide the contracted service and documented instructions, subject to the DPA.</p></LegalSection>
  <LegalSection title="5. Sharing and subprocessors"><p>We may use service providers to host the application, send transactional email, provide subscription billing, maintain backups or support service security. Current categories/providers are listed on the <Link href="/legal/subprocessors">Subprocessors page</Link>. We do not sell personal data to advertisers.</p><p>We may also disclose information where required by law or reasonably necessary to protect rights, security or the integrity of the service.</p></LegalSection>
  <LegalSection title="6. International transfers"><p>Where personal data is transferred across countries, StudioTasker uses an appropriate legal transfer mechanism where required. For EEA/UK restricted transfers, this may include applicable adequacy decisions, the European Commission’s Standard Contractual Clauses or another legally recognised safeguard. See the DPA for the controller–processor framework.</p></LegalSection>
  <LegalSection title="7. Retention"><p>We retain account and service information for as long as needed to provide StudioTasker and for legitimate security, accounting, legal and dispute-resolution requirements. Workspace data is retained during the customer relationship and then handled according to the DPA, applicable deletion requests, backup rotation and legal retention obligations.</p></LegalSection>
  <LegalSection title="8. Security"><p>StudioTasker uses technical and organisational measures designed to protect data, including role-based access, tenant isolation, secure sessions, transport encryption in production, encrypted backup procedures and restricted database access. More detail is available in the <Link href="/legal/security">Security page</Link>.</p></LegalSection>
  <LegalSection title="9. Your privacy rights"><p>Depending on applicable law, individuals may have rights to access, correct, delete, restrict or object to processing, request portability, withdraw consent where consent is the basis, and complain to a competent supervisory authority.</p><p>If your request concerns information held by a studio about you as its member or client, contact that studio first. StudioTasker will assist the studio where required by the DPA.</p></LegalSection>
  <LegalSection title="10. Children and special-category data"><p>StudioTasker is sold to businesses, not directly to children. A studio is responsible for determining whether it may lawfully process minors’ data. Unless separately agreed and technically supported, customers should not store medical records, diagnoses or other special-category/high-risk information in StudioTasker.</p></LegalSection>
  <LegalSection title="11. Cookies and browser storage"><p>See the <Link href="/legal/cookies">Cookie Policy</Link>. The core service uses authentication/session technology that is necessary to keep accounts secure. We do not describe advertising trackers as part of the current core service.</p></LegalSection>
  <LegalSection title="12. Contact"><p>Privacy questions may be sent to <strong>{op.email}</strong>. Operator address: <strong>{op.address}</strong>, {op.country}.</p></LegalSection>
 </LegalPage>
}
