-- StudioTasker executable schema is maintained exclusively in db/migrations/001_baseline.sql
-- and sequential later migrations. This former design draft was obsolete and must NEVER
-- be executed as a live schema, fixture or reference for an API or user data query.
--
-- For a controlled local isolated Postgres database:
--   npm run db:setup:local
-- For a reviewed migration on an existing database with a separate migration identity:
--   npm run db:migrate
--
-- Keep the runtime application identity distinct from migrations. Verify FORCE RLS
-- and tenant isolation before enabling customer data. Do not reproduce old auth_subject
-- DDL from historical documentation.
