const assert=require("node:assert/strict");
const fs=require("node:fs");
const client=fs.readFileSync("app/workspace/workspace-client.tsx","utf8");
const css=fs.readFileSync("app/workspace/workspace.css","utf8");
const operation=fs.readFileSync("app/workspace/studio-operations.tsx","utf8");
const workspacePage=fs.readFileSync("app/workspace/page.tsx","utf8");
const onboarding=fs.readFileSync("app/workspace/onboarding-panel.tsx","utf8");
const today=fs.readFileSync("app/today/page.tsx","utf8");
const home=fs.readFileSync("app/page.tsx","utf8");
const editorialCss=fs.readFileSync("app/editorial.css","utf8");
const layout=fs.readFileSync("app/layout.tsx","utf8");
const subscriptionRoute=fs.readFileSync("app/api/studio/subscription/route.ts","utf8");
const billing=fs.readFileSync("lib/server/billing.ts","utf8");
const billingPanel=fs.readFileSync("app/workspace/billing-panel.tsx","utf8");
const paddleWebhook=fs.readFileSync("app/api/billing/paddle-webhook/route.ts","utf8");
const turkiyePrivacy=fs.readFileSync("app/legal/turkiye-privacy/page.tsx","utf8");
const appDemo=fs.readFileSync("app/app-demo/page.tsx","utf8");
const appDemoCss=fs.readFileSync("app/app-demo/app-demo.css","utf8");
const bookingPreview=fs.readFileSync("app/book/preview/page.tsx","utf8");
const startPage=fs.readFileSync("app/start/page.tsx","utf8");
const startCss=fs.readFileSync("app/start/start.css","utf8");
const terms=fs.readFileSync("app/legal/terms/page.tsx","utf8");
const privacy=fs.readFileSync("app/legal/privacy/page.tsx","utf8");
const dpa=fs.readFileSync("app/legal/dpa/page.tsx","utf8");
const legalVersions=fs.readFileSync("lib/legal-versions.ts","utf8");
const legalHub=fs.readFileSync("app/legal/page.tsx","utf8");
const pilatesLanding=fs.readFileSync("app/pilates-studio-software/page.tsx","utf8");
const compareLanding=fs.readFileSync("app/compare/page.tsx","utf8");
const marketingCss=fs.readFileSync("app/marketing-landing.css","utf8");
const robots=fs.readFileSync("app/robots.ts","utf8");
const sitemap=fs.readFileSync("app/sitemap.ts","utf8");
const contactPage=fs.readFileSync("app/contact/page.tsx","utf8");
const contactForm=fs.readFileSync("app/contact/contact-form.tsx","utf8");
const contactRoute=fs.readFileSync("app/api/contact/route.ts","utf8");
const contactCss=fs.readFileSync("app/contact/contact.css","utf8");
const checkoutPage=fs.readFileSync("app/checkout/page.tsx","utf8");
const checkoutClient=fs.readFileSync("app/checkout/checkout-client.tsx","utf8");
const productTour=fs.readFileSync("components/product-tour-tabs.tsx","utf8");
const demoAuth=fs.readFileSync("lib/demo-auth.ts","utf8");
const legacyDemo=fs.readFileSync("app/demo/page.tsx","utf8");
assert(client.includes('role="status"'),"Async status messages must be exposed to assistive tech.");
assert(client.includes('type="email"')&&client.includes('autoComplete="username"'));
assert(client.includes('type="password"')&&client.includes("new-password"));
assert(operation.includes("StudioTasker Today")&&operation.includes("FOLLOW-UP OPPORTUNITIES")&&operation.includes("Mark contacted")&&operation.includes("Make task"),"Today dashboard and one-click actions must remain visible.");
assert(css.includes("@media(max-width:720px)")&&css.includes("@media(max-width:600px)"),"Phone layouts should be explicitly accounted for.");
assert(css.includes(":focus-visible"),"Keyboard focus should be styled.");
assert(css.includes("font-size:16px"),"Forms must avoid sub-16px input text on phones.");
assert(client.includes("MAKE STUDIOTASKER YOURS")&&client.includes("Primary brand color")&&client.includes("Today rules"),"Real workspace must expose studio appearance and operating-rule customization.");
assert(client.includes("memberTerm")&&client.includes("classTerm")&&client.includes("creditTerm")&&client.includes("/api/studio/logo"),"Real workspace must apply terminology and studio logo personalization.");
assert(css.includes("--studio-accent")&&css.includes(".rd-live-sidebar"),"Real workspace must use tenant accent color in the owner-app shell.");
assert(onboarding.includes("5-step quick start")&&onboarding.includes("mode=preview")&&onboarding.includes("Finish setup"),"Studio-owner onboarding and CSV preview must remain available.");
assert(today.includes('redirect("/app-demo?tour=1")'),"/today must redirect into the guided owner demo instead of duplicating product-tour content.");
assert(home.includes("Know what needs attention.")&&home.includes("/app-demo")&&!home.includes("/book/preview"),"Homepage must retain action-first differentiation and the owner-only app demo.");
assert(home.includes("START STUDIOTASKER")&&home.includes("WATCH 90-SEC DEMO")&&home.includes('href="/start"'),"First-fold homepage must expose obvious purchase and demo actions.");
assert(home.includes("SELF-SERVE ONBOARDING")&&home.includes("Create your studio")&&home.includes("Import by CSV with preview")&&home.includes("Keep your payment setup"),"Homepage must explain self-serve onboarding in plain language.");
assert(startPage.includes("START MONTHLY · $39.90")&&startPage.includes("START ANNUAL · $406.80/YEAR")&&startPage.includes("BEST VALUE · SAVE $72/YEAR")&&startPage.includes("$72/year lower total price")&&startPage.includes("/workspace?mode=register&plan=monthly")&&startPage.includes("/workspace?mode=register&plan=annual"),"Purchase page must expose both plans, quantify annual savings and continue into account creation.");
assert(startCss.includes("font-size:19px")&&startCss.includes("min-height:60px"),"Purchase page must keep large, older-user-friendly text and targets.");
assert(demoAuth.includes("owner@demo.studiotasker.com")&&!demoAuth.includes("member@demo.studiotasker.com"),"App demo must expose only the studio-owner sandbox account.");
assert(appDemo.includes("STUDIOTASKER TODAY")&&appDemo.includes("OWNER WORKSPACE")&&appDemo.includes("Sign in to StudioTasker"),"Owner app demo must include login and studio workspace.");
assert(["Today","Leads / CRM","Members","Classes","Follow-ups","Insights","Settings"].every(label=>appDemo.includes(label)),"Canonical owner app must expose the complete unified navigation.");
assert(appDemo.includes('view==="leads"')&&appDemo.includes('view==="settings"'),"Owner app must include Leads / CRM and Settings views.");
assert(["+ Add lead","+ Add member","+ Add follow-up"].every(label=>appDemo.includes(label))&&appDemo.includes('label={"+ Add "+singular(settings.classTerm)'),"Interactive owner demo must expose limited add actions for core records, including customized class terminology.");
assert(appDemo.includes("DEMO_ADD_LIMIT=3")&&appDemo.includes("Reset demo")&&appDemo.includes("customizationSaves>=5")&&appDemo.includes("logoUploads>=2"),"Demo mutations and customization must be explicitly limited and resettable.");
assert(appDemo.includes("removeLead")&&appDemo.includes("removeMember")&&appDemo.includes("removeClass")&&appDemo.includes("removeTask"),"Demo must let visitors remove sandbox records.");
assert(appDemo.includes("completeTask")&&appDemo.includes("advanceLead"),"Demo must teach basic workflow actions, not just display data.");
assert(["Primary brand color","Studio logo","Default landing page","Week starts","Time format","Default duration","Inactive after","Open-seat signal"].every(label=>appDemo.includes(label)),"Demo Settings must mirror the real customer customization controls.");
assert(bookingPreview.includes("studiotasker-demo-settings")&&bookingPreview.includes("studiotasker-demo-logo")&&bookingPreview.includes("demoBookings>=3"),"Booking preview must inherit demo branding and enforce a limited sandbox flow.");
assert(legacyDemo.includes('redirect("/app-demo")'),"Legacy /demo must redirect to the canonical owner app.");
assert(appDemo.includes("sessionStorage")&&appDemoCss.includes(":focus-visible")&&appDemoCss.includes("font-size:16px"),"App demo must persist only a browser-session role and remain keyboard/mobile friendly.");
assert(home.includes("/app-demo"),"Homepage must link directly to the role-based app login demo.");
assert(home.includes('href="/legal"')&&home.includes("Legal & Trust")&&!home.includes('href="/legal/terms"')&&!home.includes('href="/legal/privacy"'),"Homepage footer must keep legal navigation concise and route detailed documents through the Legal & Trust hub.");
assert(!terms.includes("Commercial legal identity not configured")&&!privacy.includes("Commercial legal identity not configured"),"Public legal documents must not expose internal setup warnings.");
assert(client.includes("registrationLegalAccepted")&&client.includes("LEGAL_ACCEPTANCE_TEXT")&&client.includes("/legal/terms")&&client.includes("/legal/dpa"),"Studio registration must use explicit legal clickwrap.");
assert(client.includes("privacyPolicyUrl")&&client.includes("Studio Privacy Policy URL"),"Real workspace must let the studio set its own Privacy Policy URL.");
assert(billingPanel.includes("LEGAL_ACCEPTANCE_TEXT")&&billingPanel.includes("Cancellation & Refund")&&billingPanel.includes("Türkiye Privacy Notice"),"Paddle checkout must require current contract acceptance while presenting privacy notices separately.");
assert(bookingPreview.includes("is responsible for the personal information")&&bookingPreview.includes("privacyPolicyUrl"),"Booking preview must identify the studio as controller and expose its privacy notice.");
assert(terms.includes("Liability")&&terms.includes("independent individual operator")&&privacy.includes("Studio member data")&&privacy.includes("independent individual operator")&&dpa.includes("controller")&&dpa.includes("Standard Contractual Clauses")&&dpa.includes("EU-region production hosting")&&turkiyePrivacy.includes("Law No. 6698")&&turkiyePrivacy.includes("No bundled consent"),"Core legal documents must cover individual operation, SaaS liability, controller/processor roles, EU safeguards and Türkiye KVKK transparency.");
assert(legalVersions.includes('terms:"2026-10-06.4"')&&legalVersions.includes('dpa:"2026-10-06.3"')&&legalVersions.includes('privacy:"2026-10-06.4"')&&legalVersions.includes('cancellation:"2026-10-06.3"')&&legalVersions.includes("LEGAL_ACCEPTANCE_TEXT"),"Legal acceptance must be tied to the current individual-operator document versions.");
assert(home.includes("ONLY $39.90 / MONTH")&&home.includes("ANNUAL · $33.90/MO")&&home.includes("SAVE $72/YEAR")&&home.includes("$406.80"),"Homepage must present a simplified monthly entry price and quantified annual value.");
assert(home.includes("<ProductTourTabs/>")&&productTour.includes('label:"Today"')&&productTour.includes('label:"Members"')&&productTour.includes('label:"Classes"')&&productTour.includes('label:"Follow-ups"'),"Homepage product tour must expose four interactive owner-workflow tabs.");
assert(home.indexOf("01 / PLAIN & SIMPLE")<home.indexOf("02 / BUILT FOR YOUR KIND OF STUDIO")&&home.indexOf("02 / BUILT FOR YOUR KIND OF STUDIO")<home.indexOf("03 / PRODUCT TOUR")&&home.indexOf("03 / PRODUCT TOUR")<home.indexOf("04 / WHY STUDIOTASKER")&&home.indexOf("04 / WHY STUDIOTASKER")<home.indexOf("05 / SELF-SERVE ONBOARDING")&&home.indexOf("05 / SELF-SERVE ONBOARDING")<home.indexOf("06 / GOOD TO KNOW"),"Homepage must follow Hero, Pricing, Studio types, Product tour, Why StudioTasker, Self-serve onboarding, FAQ.");
assert(!home.includes("See what StudioTasker tells you to do today"),"Hero purchase area must stay simplified without the extra Today text link.");
assert(["USA","CANADA","UK","EUROPE","INTERNATIONAL"].every(x=>home.includes(x))&&home.includes("Where is StudioTasker available?"),"Homepage must communicate global availability across North America and Europe.");
assert(!home.includes("One studio system.")&&!home.includes("BUILT TO TRAVEL"),"Homepage must not render the removed global positioning section.");
assert(startPage.includes("USA · Canada · UK · Europe · International")&&startPage.includes("/ month · USD"),"Purchase page must communicate global availability and USD billing.");
assert(layout.includes("Global studio management software")&&layout.includes("USA, Canada, UK, Europe and beyond"),"Public metadata must be global-first.");
assert(compareLanding.includes("STUDIOTASKER · VS. BROADER PLATFORMS"),"Neutral comparison page must remain available without cluttering the homepage navigation.");
assert(pilatesLanding.includes("PILATES / REFORMER STUDIO SOFTWARE · GLOBAL")&&pilatesLanding.includes("Reformer spots")&&pilatesLanding.includes("StudioTypeLanding"),"Pilates landing page must use the shared vertical template with Reformer-specific operations.");
assert(compareLanding.includes("STUDIOTASKER · VS. BROADER PLATFORMS")&&compareLanding.includes("Broader platforms may")&&compareLanding.includes("does not make feature claims about any named competitor"),"Neutral comparison page must stay concise and compare approaches without naming competitors.");
assert(compareLanding.includes("general product approaches only")&&compareLanding.includes("named competitor"),"Visible comparison content must remain generic and company-neutral.");
assert(marketingCss.includes(".mk-hero-grid")&&marketingCss.includes("@media(max-width:560px)"),"Acquisition landing pages must include desktop and mobile layouts.");
assert(["/pilates-studio-software","/yoga-studio-software","/barre-studio-software","/dance-studio-software","/indoor-cycling-software","/fitness-gym-software","/boutique-fitness-software","/compare"].every(x=>sitemap.includes(x))&&!sitemap.includes('["/today"'),"Sitemap must include all seven vertical SEO pages and exclude the redirected Today route.");
assert(home.includes("PILATES · YOGA · BARRE · BOUTIQUE FITNESS")&&!home.includes("ed-index-line")&&!home.includes("MADE FOR THE MOVEMENT MAKERS"),"Hero studio-type label must be clean and free of the removed decorative line and vertical copy.");
assert(!/interactive product prototype|not a live paid service|launch target|EARLY ACCESS|DEVELOPMENT PREVIEW|proposed price/i.test(home),"Public homepage must use live-service language, not pre-launch copy.");
assert(layout.includes("index: true")&&layout.includes("follow: true")&&!layout.includes("management concept"),"Public metadata must describe the live service and permit indexing.");
assert(subscriptionRoute.includes("LEGAL_PLAN_PRICE_CENTS")&&subscriptionRoute.includes("paddle.prices.get")&&subscriptionRoute.includes("paddle.transactions.create")&&subscriptionRoute.includes("customData"),"Checkout must verify the Paddle catalog server-side and bind trusted studio/price metadata before opening checkout.");
assert(editorialCss.includes(".ed-faq-list details p{font-size:16.5px")&&editorialCss.includes(".ed-topline{font-size:10.5px"),"Homepage FAQ and micro-copy must remain readable on laptop/tablet.");
assert(editorialCss.includes("max-height:calc(100svh - 110px)")&&editorialCss.includes("font-size:clamp(68px,6.45vw,118px)"),"Desktop hero must fit within the first viewport.");
assert(editorialCss.includes(".ed-buy-cta span")&&editorialCss.includes("color:#17203c!important"),"Lime purchase CTAs must use dark high-contrast text.");
assert(!client.includes("production infrastructure is configured")&&!onboarding.includes("legal launch checks")&&!workspacePage.includes("Secure backend not configured")&&!workspacePage.includes("subscription infrastructure are configured"),"Customer workspace must not expose development-stage infrastructure wording.");
assert(client.includes("pendingPlan")&&client.includes('requestedMode==="register"')&&client.includes("Complete your"),"Workspace auth must preserve plan intent from the purchase flow.");
assert(billingPanel.includes("Monthly · $39.90/month")&&billingPanel.includes("Annual · $406.80/year · save 15%")&&billingPanel.includes("Manage billing in Paddle"),"Workspace subscription controls must show the published prices and Paddle portal management.");
assert(productTour.includes("WATCH THE 90-SEC DEMO")&&home.includes("03 / PRODUCT TOUR"),"Product tour must lead directly into the guided demo.");
assert(home.includes("<Dumbbell")||home.includes("Dumbbell"),"Homepage source must use studio/fitness iconography instead of decorative star marks.");
assert(legalHub.includes('["KVKK Privacy Notice","","/legal/turkiye-privacy"]')&&!legalHub.includes("Türkiye Privacy Notice (KVKK)"),"Legal hub must show only the concise KVKK Privacy Notice title on that card.");
assert(["PILATES / REFORMER","YOGA","BARRE","DANCE","INDOOR CYCLING","FITNESS & GYM","BOUTIQUE FITNESS"].every(label=>home.includes(label)),"Homepage must show all seven supported studio-type cards.");
assert(home.includes("BUILT FOR INDEPENDENT STUDIOS WORLDWIDE")&&home.includes("no fake customer-logo wall"),"Homepage trust layer must avoid invented customer proof.");
assert(home.includes("No sales call required to see the price.")&&home.includes("without requiring an implementation consultant"),"Why StudioTasker must emphasize low-friction buying and operation.");
assert(home.includes("Start without")&&home.includes("booking a setup call.")&&home.includes("The first setup is designed to take minutes"),"Homepage must emphasize self-serve onboarding.");
assert(home.includes("ed-hero-lifestyle")&&home.includes("images.unsplash.com/photo-1717500252172-b1840ea64f05"),"Hero must include a real studio lifestyle visual alongside the product preview.");
console.log("UI smoke checks passed: labels, status messages, keyboard focus, confirmation and responsive rules.");

assert(home.includes('href="/contact"')&&home.includes(">Contact<"),"Homepage top and footer navigation must expose Contact.");
assert(contactPage.includes("support@studiotasker.com")&&contactForm.includes('SUPPORT_EMAIL="support@studiotasker.com"'),"Contact page and form must use the published StudioTasker support address.");
assert(contactForm.includes('name="name"')&&contactForm.includes('name="email"')&&contactForm.includes('name="studio"')&&contactForm.includes('name="topic"')&&contactForm.includes('name="message"')&&contactForm.includes('fetch("/api/contact"'),"Contact form must collect core enquiry fields and submit them to the server endpoint.");
assert(sitemap.includes('"/contact"'),"Sitemap must include the Contact page.");
assert(editorialCss.includes(".ed-studio-types{padding:78px 0 86px")&&editorialCss.includes(".ed-product-tour{padding:82px 0 88px")&&editorialCss.includes(".ed-why{padding:82px 0 88px")&&editorialCss.includes(".ed-onboarding{padding:82px 0 88px")&&editorialCss.includes(".ed-faq{padding:76px 0 84px"),"Desktop homepage sections must use the tighter conversion-focused rhythm.");
assert(home.includes("StudioTasker keeps member relationships, classes, package entitlements and follow-ups in one place for independent studios worldwide."),"Homepage hero must use the simplified worldwide positioning copy.");
assert(home.includes("Useful software.")&&home.includes("Without the enterprise baggage."),"Why StudioTasker section must communicate the focused non-enterprise position.");
assert(home.includes("Your member payments stay with the studio")&&home.includes("StudioTasker bills only for its software."),"Homepage must clearly state that StudioTasker does not take over member payments.");
assert(home.includes('className="ed-pricing-kicker"')&&!home.includes("Even better yearly.")&&!home.includes("Monthly keeps things flexible at $39.90."),"Pricing must go directly from the 01 kicker into the price cards without the large intro block.");
assert(!contactPage.includes("feedback — send us")&&contactPage.includes("feedback. Send us a message"),"Contact marketing copy must avoid long dash punctuation.");


assert(contactForm.includes('fetch("/api/contact"')&&!contactForm.includes('window.location.href="mailto:'),"Contact form must submit to the server API instead of opening the visitor's email app.");
assert(contactForm.includes("SEND MESSAGE")&&contactForm.includes("Message sent."),"Contact form must expose real sending and success states.");
assert(contactRoute.includes("nodemailer")&&contactRoute.includes("SMTP_HOST")&&contactRoute.includes("replyTo:email")&&contactRoute.includes("support@studiotasker.com"),"Contact API must deliver enquiries through configured SMTP to StudioTasker support.");
assert(contactCss.includes("@media(min-width:901px)")&&contactCss.includes("min-height:100svh")&&contactCss.includes("max-height:760px"),"Contact page must use a compact single-viewport desktop layout.");


assert(appDemo.includes("DEMO_SESSION_SECONDS=60*60")&&appDemo.includes("studiotasker-demo-session-start")&&appDemo.includes("studiotasker-demo-session-expired"),"Demo must enforce a persistent 60-minute per-tab session.");
assert(appDemo.includes("60-MINUTE DEMO COMPLETE")&&appDemo.includes("CHOOSE A PLAN")&&appDemo.includes("expireDemo()"),"Expired demo must reset and end at a plan-selection screen.");
assert(appDemo.includes("Resetting data does not restart the 60-minute session.")&&appDemo.includes("demoTimeLabel(demoRemaining)"),"Demo must disclose that resets do not extend the session and show time remaining.");
assert(appDemoCss.includes("sad-demo-expired")&&appDemoCss.includes("sad-expired-card"),"Timed demo expiry screen must be styled.");

assert(startPage.includes('className="st-start-intro-meta"'),"Start page back link and kicker must share a deliberate meta row.");
assert(startCss.includes(".st-start-intro-meta{display:flex")&&startCss.includes("padding:38px 0 76px")&&!startCss.includes("margin:-20px 0 28px"),"Start page hero spacing and global band must avoid overlap and negative margins.");

const classOs=fs.readFileSync("app/workspace/class-based-operations.tsx","utf8");
const classEngine=fs.readFileSync("lib/server/class-based-os.ts","utf8");
const classMigration=fs.readFileSync("db/migrations/015_class_based_os.sql","utf8");
const staffApi=fs.readFileSync("app/api/studio/staff/route.ts","utf8");
const insightsApi=fs.readFileSync("app/api/studio/insights/route.ts","utf8");
assert(classMigration.includes("Indoor cycling")&&classMigration.includes("Fitness & Gym")&&classMigration.includes("studio_staff")&&classMigration.includes("spot_number")&&classMigration.includes("cancellation_type")&&classMigration.includes("waiver_status"),"Class-based OS migration must cover verticals, staff, spots, cancellations and waivers.");
assert(classEngine.includes("assignSpotToBooking")&&classEngine.includes("cancelBookingWithRules")&&classEngine.includes("setBookingNoShow")&&classEngine.includes("booking.promoted"),"Booking engine must integrate spot assignment, waitlist promotion, late cancellation and no-show.");
assert(classOs.includes("Repeat weekly")&&classOs.includes("Join waitlist")&&classOs.includes("No-show")&&classOs.includes("Numbered equipment / spot booking")&&classOs.includes("Staff & instructor roster"),"Workspace must expose the core class-based studio workflows.");
assert(classOs.includes("30-day operational insights")&&insightsApi.includes("no_show")&&insightsApi.includes("late_cancels")&&insightsApi.includes("trialConversion"),"Insights must report utilization, attendance, no-shows, late cancels and trial conversion.");
assert(staffApi.includes("studio_staff")&&client.includes("waiverStatus")&&client.includes("tags:editForm.tags"),"Workspace must integrate staff roster plus member tags and waiver state.");

assert(client.includes("Parent / guardian contact")&&client.includes("Related / emergency contact")&&client.includes("relatedContactName")&&client.includes("relatedContactRole"),"Dance and other studios must support an optional related contact on member records.");

assert(["PILATES / REFORMER","YOGA","BARRE","DANCE","INDOOR CYCLING","FITNESS & GYM","BOUTIQUE FITNESS"].every(x=>home.includes(x)),"Homepage Studio types must cover all seven supported class-based verticals.");
assert(["Indoor cycling","Fitness &amp; Gym","Boutique fitness"].every(x=>appDemo.includes(x))&&appDemo.includes("EQUIPMENT SPOTS")&&appDemo.includes("NO-SHOW"),"Owner demo must reflect the expanded studio presets and class operations.");

assert(client.includes("ACTIVE PRESET")&&client.includes("studioPresetProfile(settings.focus)")&&client.includes("Recommended formats:"),"Workspace Settings must explain the active vertical preset and recommended class formats.");
assert(client.includes("Parent / guardian contact")&&client.includes("Operational tags")&&client.includes("Waiver status"),"Member creation must capture class-based studio context at first entry.");
assert(classOs.includes("Popular time slots")&&classOs.includes("editingStaff")&&classOs.includes("Staff details updated."),"Class-based operations must expose time-slot reporting and editable staff roster.");
assert(insightsApi.includes("time_slot")&&insightsApi.includes("timeSlots:timeSlots.rows"),"Insights API must include popular class time slots.");

assert(billingPanel.includes('variant:"one-page"')&&billingPanel.includes('successUrl:"/workspace?billing=success"'),"Paddle checkout must use the one-page overlay and a workspace success URL.");
assert(paddleWebhook.includes("BILLING_ALLOW_SANDBOX_TEST")&&paddleWebhook.includes("PADDLE_SANDBOX_ALLOWED_ORIGIN")&&paddleWebhook.includes("approvedStaging"),"Paddle sandbox webhooks must support only an explicitly configured staging origin.");

assert(layout.includes('metadataBase: new URL("https://www.studiotasker.com")')&&robots.includes("https://www.studiotasker.com")&&sitemap.includes("https://www.studiotasker.com"),"StudioTasker canonical URLs must use the final www.studiotasker.com domain.");
assert(checkoutPage.includes("Secure checkout")&&checkoutClient.includes('params.get("_ptxn")')&&checkoutClient.includes("NEXT_PUBLIC_PADDLE_CLIENT_TOKEN")&&checkoutClient.includes("paddle.Checkout.open"),"Public checkout page must handle Paddle transaction links on the final domain.");

assert(billing.includes("sandboxStaging")&&billing.includes("BILLING_ALLOW_SANDBOX_TEST")&&billing.includes("PADDLE_SANDBOX_ALLOWED_ORIGIN")&&billing.includes('process.env.PADDLE_ENV!=="production"'),"Sandbox entitlements must only work on the explicitly configured non-production test origin.");

const studioLanding=fs.readFileSync("app/studio-type-landing.tsx","utf8");
const verticalPages=["yoga","barre","dance","indoor-cycling","fitness-gym","boutique-fitness"].map(x=>fs.readFileSync("app/"+x+"-software/page.tsx","utf8"));
assert(studioLanding.includes("FAQPage")&&studioLanding.includes("STUDIOTASKER TODAY")&&studioLanding.includes("ONE STUDIO · FULL WORKSPACE"),"Shared vertical landing template must include SEO FAQ schema, operational differentiation and pricing.");
assert(verticalPages.every(x=>x.includes("StudioTypeLanding")&&x.includes("alternates:{canonical:")),"Every new studio-type SEO route must use the shared template and declare its canonical URL.");
assert(home.includes('href:"/pilates-studio-software"')&&home.includes('href:"/yoga-studio-software"')&&home.includes('href:"/dance-studio-software"')&&home.includes('href:"/fitness-gym-software"'),"Homepage studio-type cards must lead into the dedicated vertical pages.");
