const assert=require("node:assert/strict");
const fs=require("node:fs");
const client=fs.readFileSync("app/workspace/workspace-client.tsx","utf8");
const css=fs.readFileSync("app/workspace/workspace.css","utf8");
const operation=fs.readFileSync("app/workspace/studio-operations.tsx","utf8");
const onboarding=fs.readFileSync("app/workspace/onboarding-panel.tsx","utf8");
const today=fs.readFileSync("app/today/page.tsx","utf8");
const home=fs.readFileSync("app/page.tsx","utf8");
const appDemo=fs.readFileSync("app/app-demo/page.tsx","utf8");
const appDemoCss=fs.readFileSync("app/app-demo/app-demo.css","utf8");
const demoAuth=fs.readFileSync("lib/demo-auth.ts","utf8");
assert(client.includes('role="status"'),"Async status messages must be exposed to assistive tech.");
assert(client.includes('type="email"')&&client.includes('autoComplete="username"'));
assert(client.includes('type="password"')&&client.includes("new-password"));
assert(operation.includes("StudioTasker Today")&&operation.includes("REVENUE RESCUE")&&operation.includes("Mark contacted")&&operation.includes("Make task"),"Today dashboard and one-click actions must remain visible.");
assert(css.includes("@media(max-width:720px)")&&css.includes("@media(max-width:600px)"),"Phone layouts should be explicitly accounted for.");
assert(css.includes(":focus-visible"),"Keyboard focus should be styled.");
assert(css.includes("font-size:16px"),"Forms must avoid sub-16px input text on phones.");
assert(onboarding.includes("5-step quick start")&&onboarding.includes("mode=preview")&&onboarding.includes("Finish setup"),"Studio-owner onboarding and CSV preview must remain available.");
assert(today.includes("Know what your")&&today.includes("REVENUE RESCUE")&&today.includes("Mark contacted")&&today.includes("StudioTasker does not process member payments"),"StudioTasker Today preview must expose studio-only action-first differentiation.");
assert(home.includes("what needs attention")&&home.includes("/today")&&home.includes("/app-demo")&&!home.includes("/book/preview"),"Homepage must lead with Today differentiation and the owner-only app demo.");
assert(demoAuth.includes("owner@demo.studiotasker.com")&&!demoAuth.includes("member@demo.studiotasker.com"),"App demo must expose only the studio-owner sandbox account.");
assert(appDemo.includes("STUDIOTASKER TODAY")&&appDemo.includes("OWNER WORKSPACE")&&appDemo.includes("Sign in to StudioTasker"),"Owner app demo must include login and studio workspace.");
assert(appDemo.includes("sessionStorage")&&appDemoCss.includes(":focus-visible")&&appDemoCss.includes("font-size:16px"),"App demo must persist only a browser-session role and remain keyboard/mobile friendly.");
assert(home.includes("/app-demo"),"Homepage must link directly to the role-based app login demo.");
console.log("UI smoke checks passed: labels, status messages, keyboard focus, confirmation and responsive rules.");
