const assert=require("node:assert/strict");
const fs=require("node:fs");
const client=fs.readFileSync("app/workspace/workspace-client.tsx","utf8");
const css=fs.readFileSync("app/workspace/workspace.css","utf8");
const operation=fs.readFileSync("app/workspace/studio-operations.tsx","utf8");
const workspacePage=fs.readFileSync("app/workspace/page.tsx","utf8");
const onboarding=fs.readFileSync("app/workspace/onboarding-panel.tsx","utf8");
const today=fs.readFileSync("app/today/page.tsx","utf8");
const home=fs.readFileSync("app/page.tsx","utf8");
const editorialCss=fs.readFileSync("app/editorial.css","utf8");
const layout=fs.readFileSync("app/layout.tsx","utf8");
const subscriptionRoute=fs.readFileSync("app/api/studio/subscription/route.ts","utf8");
const billingPanel=fs.readFileSync("app/workspace/billing-panel.tsx","utf8");
const turkiyePrivacy=fs.readFileSync("app/legal/turkiye-privacy/page.tsx","utf8");
const appDemo=fs.readFileSync("app/app-demo/page.tsx","utf8");
const appDemoCss=fs.readFileSync("app/app-demo/app-demo.css","utf8");
const bookingPreview=fs.readFileSync("app/book/preview/page.tsx","utf8");
const startPage=fs.readFileSync("app/start/page.tsx","utf8");
const startCss=fs.readFileSync("app/start/start.css","utf8");
const terms=fs.readFileSync("app/legal/terms/page.tsx","utf8");
const privacy=fs.readFileSync("app/legal/privacy/page.tsx","utf8");
const dpa=fs.readFileSync("app/legal/dpa/page.tsx","utf8");
const legalVersions=fs.readFileSync("lib/legal-versions.ts","utf8");
const legalHub=fs.readFileSync("app/legal/page.tsx","utf8");
const pilatesLanding=fs.readFileSync("app/pilates-studio-software/page.tsx","utf8");
const compareLanding=fs.readFileSync("app/compare/page.tsx","utf8");
const marketingCss=fs.readFileSync("app/marketing-landing.css","utf8");
const sitemap=fs.readFileSync("app/sitemap.ts","utf8");
const demoAuth=fs.readFileSync("lib/demo-auth.ts","utf8");
const legacyDemo=fs.readFileSync("app/demo/page.tsx","utf8");
assert(client.includes('role="status"'),"Async status messages must be exposed to assistive tech.");
assert(client.includes('type="email"')&&client.includes('autoComplete="username"'));
assert(client.includes('type="password"')&&client.includes("new-password"));
assert(operation.includes("StudioTasker Today")&&operation.includes("REVENUE RESCUE")&&operation.includes("Mark contacted")&&operation.includes("Make task"),"Today dashboard and one-click actions must remain visible.");
assert(css.includes("@media(max-width:720px)")&&css.includes("@media(max-width:600px)"),"Phone layouts should be explicitly accounted for.");
assert(css.includes(":focus-visible"),"Keyboard focus should be styled.");
assert(css.includes("font-size:16px"),"Forms must avoid sub-16px input text on phones.");
assert(client.includes("MAKE STUDIOTASKER YOURS")&&client.includes("Primary brand color")&&client.includes("Today rules"),"Real workspace must expose studio appearance and operating-rule customization.");
assert(client.includes("memberTerm")&&client.includes("classTerm")&&client.includes("creditTerm")&&client.includes("/api/studio/logo"),"Real workspace must apply terminology and studio logo personalization.");
assert(css.includes("--studio-accent")&&css.includes(".rd-live-sidebar"),"Real workspace must use tenant accent color in the owner-app shell.");
assert(onboarding.includes("5-step quick start")&&onboarding.includes("mode=preview")&&onboarding.includes("Finish setup"),"Studio-owner onboarding and CSV preview must remain available.");
assert(today.includes("Know what your")&&today.includes("REVENUE RESCUE")&&today.includes("Mark contacted")&&today.includes("StudioTasker does not process member payments"),"StudioTasker Today preview must expose studio-only action-first differentiation.");
assert(home.includes("what needs attention")&&home.includes("/today")&&home.includes("/app-demo")&&!home.includes("/book/preview"),"Homepage must retain Today differentiation and the owner-only app demo.");
assert(home.includes("START STUDIOTASKER")&&home.includes("TRY THE DEMO")&&home.includes('href="/start"'),"First-fold homepage must expose obvious purchase and demo actions.");
assert(home.includes("Three steps.")&&home.includes("Choose your plan")&&home.includes("Create your studio"),"Homepage must explain the buying/onboarding path in plain language.");
assert(startPage.includes("START MONTHLY · $39.90")&&startPage.includes("START ANNUAL · $406.80/YEAR")&&startPage.includes("/workspace?mode=register&plan=monthly")&&startPage.includes("/workspace?mode=register&plan=annual"),"Purchase page must expose both plans and continue into account creation.");
assert(startCss.includes("font-size:19px")&&startCss.includes("min-height:60px"),"Purchase page must keep large, older-user-friendly text and targets.");
assert(demoAuth.includes("owner@demo.studiotasker.com")&&!demoAuth.includes("member@demo.studiotasker.com"),"App demo must expose only the studio-owner sandbox account.");
assert(appDemo.includes("STUDIOTASKER TODAY")&&appDemo.includes("OWNER WORKSPACE")&&appDemo.includes("Sign in to StudioTasker"),"Owner app demo must include login and studio workspace.");
assert(["Today","Leads / CRM","Members","Classes","Follow-ups","Insights","Settings"].every(label=>appDemo.includes(label)),"Canonical owner app must expose the complete unified navigation.");
assert(appDemo.includes('view==="leads"')&&appDemo.includes('view==="settings"'),"Owner app must include Leads / CRM and Settings views.");
assert(["+ Add lead","+ Add member","+ Add follow-up"].every(label=>appDemo.includes(label))&&appDemo.includes('label={"+ Add "+singular(settings.classTerm)'),"Interactive owner demo must expose limited add actions for core records, including customized class terminology.");
assert(appDemo.includes("DEMO_ADD_LIMIT=3")&&appDemo.includes("Reset demo")&&appDemo.includes("customizationSaves>=5")&&appDemo.includes("logoUploads>=2"),"Demo mutations and customization must be explicitly limited and resettable.");
assert(appDemo.includes("removeLead")&&appDemo.includes("removeMember")&&appDemo.includes("removeClass")&&appDemo.includes("removeTask"),"Demo must let visitors remove sandbox records.");
assert(appDemo.includes("completeTask")&&appDemo.includes("advanceLead"),"Demo must teach basic workflow actions, not just display data.");
assert(["Primary brand color","Studio logo","Default landing page","Week starts","Time format","Default duration","Inactive after","Open-seat signal"].every(label=>appDemo.includes(label)),"Demo Settings must mirror the real customer customization controls.");
assert(bookingPreview.includes("studiotasker-demo-settings")&&bookingPreview.includes("studiotasker-demo-logo")&&bookingPreview.includes("demoBookings>=3"),"Booking preview must inherit demo branding and enforce a limited sandbox flow.");
assert(legacyDemo.includes('redirect("/app-demo")'),"Legacy /demo must redirect to the canonical owner app.");
assert(appDemo.includes("sessionStorage")&&appDemoCss.includes(":focus-visible")&&appDemoCss.includes("font-size:16px"),"App demo must persist only a browser-session role and remain keyboard/mobile friendly.");
assert(home.includes("/app-demo"),"Homepage must link directly to the role-based app login demo.");
assert(home.includes('href="/legal"')&&home.includes("Legal & Trust")&&!home.includes('href="/legal/terms"')&&!home.includes('href="/legal/privacy"'),"Homepage footer must keep legal navigation concise and route detailed documents through the Legal & Trust hub.");
assert(!terms.includes("Commercial legal identity not configured")&&!privacy.includes("Commercial legal identity not configured"),"Public legal documents must not expose internal setup warnings.");
assert(client.includes("registrationLegalAccepted")&&client.includes("LEGAL_ACCEPTANCE_TEXT")&&client.includes("/legal/terms")&&client.includes("/legal/dpa"),"Studio registration must use explicit legal clickwrap.");
assert(client.includes("privacyPolicyUrl")&&client.includes("Studio Privacy Policy URL"),"Real workspace must let the studio set its own Privacy Policy URL.");
assert(billingPanel.includes("LEGAL_ACCEPTANCE_TEXT")&&billingPanel.includes("Cancellation & Refund")&&billingPanel.includes("Türkiye Privacy Notice"),"Paddle checkout must require current contract acceptance while presenting privacy notices separately.");
assert(bookingPreview.includes("is responsible for the personal information")&&bookingPreview.includes("privacyPolicyUrl"),"Booking preview must identify the studio as controller and expose its privacy notice.");
assert(terms.includes("Liability")&&terms.includes("independent individual operator")&&privacy.includes("Studio member data")&&privacy.includes("independent individual operator")&&dpa.includes("controller")&&dpa.includes("Standard Contractual Clauses")&&dpa.includes("EU-region production hosting")&&turkiyePrivacy.includes("Law No. 6698")&&turkiyePrivacy.includes("No bundled consent"),"Core legal documents must cover individual operation, SaaS liability, controller/processor roles, EU safeguards and Türkiye KVKK transparency.");
assert(legalVersions.includes('terms:"2026-10-06.4"')&&legalVersions.includes('dpa:"2026-10-06.3"')&&legalVersions.includes('privacy:"2026-10-06.4"')&&legalVersions.includes('cancellation:"2026-10-06.3"')&&legalVersions.includes("LEGAL_ACCEPTANCE_TEXT"),"Legal acceptance must be tied to the current individual-operator document versions.");
assert(home.includes("$39.90")&&home.includes("$33.90/month")&&home.includes("$406.80")&&home.includes("save 15%"),"Homepage must publish the current monthly and annual StudioTasker prices.");
assert(["USA","CANADA","UK","EUROPE","INTERNATIONAL"].every(x=>home.includes(x))&&home.includes("Where is StudioTasker available?"),"Homepage must communicate global availability across North America and Europe.");
assert(!home.includes("One studio system.")&&!home.includes("BUILT TO TRAVEL"),"Homepage must not render the removed global positioning section.");
assert(startPage.includes("USA · Canada · UK · Europe · International")&&startPage.includes("/ month · USD"),"Purchase page must communicate global availability and USD billing.");
assert(layout.includes("Global studio management software")&&layout.includes("USA, Canada, UK, Europe and beyond"),"Public metadata must be global-first.");
assert(home.includes("/compare")&&home.includes("VS. others"),"Homepage must retain the neutral comparison page outside the simplified footer.");
assert(pilatesLanding.includes("PILATES STUDIO SOFTWARE · GLOBAL")&&pilatesLanding.includes("REFORMER PILATES")&&pilatesLanding.includes("$39.90 USD")&&pilatesLanding.includes("FAQPage"),"Pilates landing page must target global Pilates/Reformer studios with price and FAQ schema.");
assert(compareLanding.includes("STUDIOTASKER · VS. OTHERS")&&compareLanding.includes("Other platforms may")&&compareLanding.includes("not a claim about any specific company"),"Neutral comparison page must compare product approaches without naming competitors.");
assert(compareLanding.includes("not a claim about any specific company")||compareLanding.includes("rather than making claims about any specific company"),"Visible comparison content must remain generic and company-neutral.");
assert(marketingCss.includes(".mk-hero-grid")&&marketingCss.includes("@media(max-width:560px)"),"Acquisition landing pages must include desktop and mobile layouts.");
assert(sitemap.includes("/pilates-studio-software")&&sitemap.includes("/compare"),"Sitemap must include the neutral comparison page.");
assert(home.includes("PILATES · YOGA · BARRE · BOUTIQUE FITNESS")&&!home.includes("ed-index-line")&&!home.includes("MADE FOR THE MOVEMENT MAKERS"),"Hero studio-type label must be clean and free of the removed decorative line and vertical copy.");
assert(!/interactive product prototype|not a live paid service|launch target|EARLY ACCESS|DEVELOPMENT PREVIEW|proposed price/i.test(home),"Public homepage must use live-service language, not pre-launch copy.");
assert(layout.includes("index: true")&&layout.includes("follow: true")&&!layout.includes("management concept"),"Public metadata must describe the live service and permit indexing.");
assert(subscriptionRoute.includes("LEGAL_PLAN_PRICE_CENTS")&&subscriptionRoute.includes("paddle.prices.get")&&subscriptionRoute.includes("paddle.transactions.create")&&subscriptionRoute.includes("customData"),"Checkout must verify the Paddle catalog server-side and bind trusted studio/price metadata before opening checkout.");
assert(editorialCss.includes(".ed-faq-list details p{font-size:16.5px")&&editorialCss.includes(".ed-topline{font-size:10.5px"),"Homepage FAQ and micro-copy must remain readable on laptop/tablet.");
assert(editorialCss.includes("max-height:calc(100svh - 110px)")&&editorialCss.includes("font-size:clamp(68px,6.45vw,118px)"),"Desktop hero must fit within the first viewport.");
assert(editorialCss.includes(".ed-buy-cta span")&&editorialCss.includes("color:#17203c!important"),"Lime purchase CTAs must use dark high-contrast text.");
assert(!client.includes("production infrastructure is configured")&&!onboarding.includes("legal launch checks")&&!workspacePage.includes("Secure backend not configured")&&!workspacePage.includes("subscription infrastructure are configured"),"Customer workspace must not expose development-stage infrastructure wording.");
assert(client.includes("pendingPlan")&&client.includes('requestedMode==="register"')&&client.includes("Complete your"),"Workspace auth must preserve plan intent from the purchase flow.");
assert(billingPanel.includes("Monthly · $39.90/month")&&billingPanel.includes("Annual · $406.80/year · save 15%")&&billingPanel.includes("Manage billing in Paddle"),"Workspace subscription controls must show the published prices and Paddle portal management.");
assert(home.includes("STEP INSIDE THE APP")&&home.includes("THE STUDIO EDIT")&&!home.includes("VOL. 01")&&home.includes("ed-window-app-cta"),"Studio edit area must use the large guided-demo CTA without the old volume label.");
assert(home.includes("<Dumbbell")||home.includes("Dumbbell"),"Homepage source must use studio/fitness iconography instead of decorative star marks.");
assert(legalHub.includes("KVKK Privacy Notice")&&!legalHub.includes("Türkiye Privacy Notice (KVKK)"),"Legal hub must use the concise KVKK Privacy Notice title.");
console.log("UI smoke checks passed: labels, status messages, keyboard focus, confirmation and responsive rules.");
