import {LegalPage,LegalSection} from "../../../components/legal-page";
import {LEGAL_VERSIONS} from "../../../lib/legal-versions";
export const metadata={title:"Cancellation & Refund Policy | StudioTasker"};
export default function Cancellation(){
 return <LegalPage title="Cancellation & Refund Policy" kicker="BILLING / PADDLE MERCHANT OF RECORD" version={LEGAL_VERSIONS.cancellation}>
  <LegalSection title="1. Who handles payment and refunds"><p>StudioTasker subscriptions are sold through Paddle, StudioTasker’s authorised reseller and Merchant of Record. Paddle processes the buyer transaction, applicable transaction taxes, buyer billing documents, payment-related support and refunds. StudioTasker does not issue a buyer refund directly outside Paddle for a Paddle transaction.</p></LegalSection>
  <LegalSection title="2. Monthly plan"><p>The monthly StudioTasker plan is $39.90 per studio per month and renews monthly until cancelled. Cancellation normally stops the next renewal and access ordinarily continues through the already-paid billing period, subject to Paddle’s buyer terms, applicable law and any earlier suspension necessary for fraud, security or material misuse.</p></LegalSection>
  <LegalSection title="3. Annual plan"><p>The annual plan is $406.80 per studio per year, equivalent to $33.90 per month when prepaid (approximately 15% less than paying monthly for twelve months). It renews annually until cancelled. Cancellation normally stops the next annual renewal and does not convert the current annual period into monthly billing.</p></LegalSection>
  <LegalSection title="4. Refunds and mandatory rights"><p>Unless required by applicable law or approved under Paddle’s applicable refund rules, transactions are generally non-refundable. Paddle’s published Refund Policy and Buyer Terms govern the transaction and may provide withdrawal/refund rights that cannot lawfully be excluded. If StudioTasker agrees that a refund is appropriate, the refund is requested or approved through Paddle rather than paid directly to the buyer.</p><p><a href="https://www.paddle.com/legal/refund-policy" target="_blank" rel="noreferrer">Paddle Refund Policy</a> · <a href="https://www.paddle.com/legal/buyer-terms" target="_blank" rel="noreferrer">Paddle Buyer Terms</a></p></LegalSection>
  <LegalSection title="5. How to cancel or manage billing"><p>Customers can manage the subscription, payment method and cancellation through Paddle’s authenticated Customer Portal made available from the StudioTasker owner workspace. Payment, invoice or refund questions may also be handled through Paddle’s buyer-support channels.</p></LegalSection>
  <LegalSection title="6. Failed payments and recovery"><p>If a renewal payment fails, Paddle may retry payment and place the subscription into a past-due state. StudioTasker may provide a short technical grace period to avoid an abrupt operational lockout while Paddle’s recovery process runs. Continued non-payment may result in loss of normal workspace access after that grace period.</p></LegalSection>
  <LegalSection title="7. Data before account closure"><p>Before requesting studio closure, Customer should export data it needs to keep. The authenticated closure form records a request but does not cancel Paddle billing or erase a studio automatically. Billing must be managed through Paddle; deletion and limited retention follow verified review under the Terms, Privacy Policy, DPA and applicable law.</p></LegalSection>
  <LegalSection title="8. Member payments are separate"><p>This policy concerns the studio’s subscription to StudioTasker. It does not govern refunds or cancellations for a studio’s own memberships, classes or packages sold to its members; those remain entirely the responsibility of the studio and its own payment providers.</p></LegalSection>
 </LegalPage>
}
