import Link from "next/link";
import {LegalPage,LegalSection} from "../../../components/legal-page";
import {LEGAL_VERSIONS} from "../../../lib/legal-versions";
import {legalOperator} from "../../../lib/server/legal-config";
export const metadata={title:"Terms of Service — StudioTasker"};
export default function Terms(){
 const op=legalOperator();
 return <LegalPage title="Terms of Service" kicker="STUDIOTASKER / SAAS AGREEMENT" version={LEGAL_VERSIONS.terms}>
  <LegalSection title="1. Agreement and authority"><p>These Terms govern access to and use of StudioTasker by the studio or other business customer that creates a workspace or purchases a subscription (“Customer”). By creating a studio account, accepting these Terms or using the paid service, the person acting for Customer confirms that they are authorised to bind Customer.</p><p>StudioTasker is operated by an <strong>independent individual operator based in {op.country}</strong>, not by a company unless the operator structure is later changed and the Terms are updated. {op.configured?<>The contracting operator is <strong>{op.name}</strong>, with the contact details shown at the end of this document.</>:<>The operator&apos;s full legal identity and service address are presented before paid service activation and recorded with the applicable contract acceptance.</>}</p></LegalSection>
  <LegalSection title="2. The service"><p>StudioTasker is business software for studio operations, including customer relationship management, class scheduling, studio-managed bookings, attendance, internal package/credit entitlement tracking, follow-ups, reports and configurable studio workflows.</p><p><strong>StudioTasker does not collect or settle payments from a studio’s members.</strong> Member prices, memberships, class-pack sales, refunds and merchant relationships remain between Customer and its own members and payment providers.</p></LegalSection>
  <LegalSection title="3. Subscription and billing"><p>The standard monthly subscription is <strong>$39.90 per studio per month</strong>. The annual subscription is <strong>$418.80 per studio per year</strong>, equivalent to $34.90 per month when prepaid annually. Taxes may be added where legally required.</p><p>Subscriptions renew automatically for the same billing period until cancelled. Payment-card information is handled by the designated subscription billing provider and is not stored in StudioTasker’s application database. Additional billing rules are in the <Link href="/legal/cancellation">Cancellation & Refund Policy</Link>.</p></LegalSection>
  <LegalSection title="4. Customer accounts and security"><p>Customer is responsible for maintaining accurate account information, protecting credentials, controlling staff access and promptly disabling access that is no longer authorised. Customer must not share owner credentials between unrelated persons.</p><p>Customer must notify StudioTasker promptly if it reasonably suspects unauthorised access to its workspace.</p></LegalSection>
  <LegalSection title="5. Customer data and lawful use"><p>Customer retains responsibility for the lawfulness, accuracy and content of data it enters into StudioTasker. Customer must have an appropriate legal basis for personal data it uploads or otherwise processes through the service and must provide required notices to its members, prospects and staff.</p><p>Unless separately agreed in writing, Customer must not use StudioTasker to store payment-card numbers, government identity documents, medical records, clinical diagnoses, biometric templates, criminal-offence data or other special-category/high-risk data that the service is not designed to handle.</p></LegalSection>
  <LegalSection title="6. Data protection"><p>For account, subscription, security and direct service-relationship data, StudioTasker may act as controller as described in the <Link href="/legal/privacy">Privacy Policy</Link>. For personal data that Customer uploads about its own members, leads or staff for Customer’s purposes, Customer generally acts as controller and StudioTasker acts as processor under the <Link href="/legal/dpa">Data Processing Agreement</Link>.</p></LegalSection>
  <LegalSection title="7. Acceptable use"><p>Customer must not: use the service unlawfully; attempt to gain access to another studio’s data; probe or bypass security controls; upload malware; use the service to harass, discriminate against or unlawfully profile individuals; resell access without written permission; or interfere with service availability.</p><p>StudioTasker may suspend access where reasonably necessary to protect security, comply with law, prevent material misuse or address a serious payment default. Where practical, reasonable notice will be provided.</p></LegalSection>
  <LegalSection title="8. Intellectual property"><p>StudioTasker and its software, design, documentation and service marks remain the property of the operator and its licensors. Customer receives a limited, non-exclusive, non-transferable right to use the service during an active subscription for its internal studio operations.</p><p>Customer retains ownership of its own content and grants StudioTasker only the rights reasonably necessary to host, process, back up and transmit that content to provide the service.</p></LegalSection>
  <LegalSection title="9. Service availability and changes"><p>StudioTasker is provided as an online software service and may require maintenance, security updates and feature changes. No uninterrupted or error-free operation is guaranteed unless a separate written service-level agreement states otherwise. Material changes that substantially reduce paid core functionality will be communicated where reasonably practicable.</p></LegalSection>
  <LegalSection title="10. Warranties and business decisions"><p>StudioTasker is operational software, not legal, medical, tax, accounting or financial advice. Suggestions such as follow-up priorities or operational signals are aids for staff judgment and do not guarantee revenue, retention or business outcomes.</p><p>To the maximum extent permitted by applicable law, implied warranties are excluded except where they cannot legally be excluded.</p></LegalSection>
  <LegalSection title="11. Liability"><p>To the maximum extent permitted by law, neither party is liable for indirect, incidental, special or consequential loss, including loss of profit, goodwill or business opportunity, except where such limitation is prohibited by law.</p><p>Subject to any liability that cannot legally be limited, the operator’s aggregate liability arising from the service will not exceed the subscription fees paid or payable by Customer for StudioTasker during the twelve months preceding the event giving rise to the claim. Nothing in these Terms limits liability for fraud, wilful misconduct or any other liability that applicable law does not permit to be limited.</p></LegalSection>
  <LegalSection title="12. Termination and data"><p>Customer may cancel in accordance with the <Link href="/legal/cancellation">Cancellation & Refund Policy</Link>. On termination, Customer should export information it needs to retain. StudioTasker may retain limited information where necessary for security, dispute resolution, accounting, legal obligations and backup rotation, then delete or anonymise data according to applicable retention procedures and the DPA.</p></LegalSection>
  <LegalSection title="13. Governing law and disputes"><p>{op.configured?<>These Terms are governed by <strong>{op.governingLaw}</strong>, subject to mandatory rules that may apply regardless of this choice. The agreed jurisdiction is <strong>{op.jurisdiction}</strong>, except where applicable law requires another forum.</>:<>The governing law and dispute forum applicable to a paid subscription will be presented with the operator&apos;s completed legal details before paid service activation, subject in all cases to mandatory rules that cannot be excluded.</>}</p></LegalSection>
  <LegalSection title="14. Changes to these Terms"><p>StudioTasker may update these Terms for legal, security, operational or product reasons. The effective version is identified above. Where a change materially affects Customer’s rights or obligations, StudioTasker will provide appropriate notice and may require a new affirmative acceptance before continued paid use.</p></LegalSection>
  <LegalSection title="15. Contact"><p>{op.email?<>Legal and contractual questions may be sent to <strong>{op.email}</strong>.</>:<>A dedicated legal contact is provided before paid service activation. Product and legal contact details are kept separate from any future company structure.</>}</p></LegalSection>
 </LegalPage>
}
