"use client";
import {useCallback,useEffect,useState,type FormEvent} from "react";
import {localDateTimeToUTC} from "../../lib/studio-timezone";

export type WorkspaceSection="today"|"classes"|"members"|"followups"|"insights"|"settings";
export type WorkspacePreferences={
 timezone:string;timeFormat:"24h"|"12h";classTerm:string;memberTerm:string;creditTerm:string;
 defaultClassDuration:number;defaultClassCapacity:number;defaultRoom:string;
 inactiveDays:number;lowCreditsThreshold:number;renewalWindowDays:number;trialFollowupHours:number;packageReviewHours:number;openSeatsThreshold:number;
};
type ClassRow={id:string;title:string;instructor:string;room:string;starts_at:string;duration_minutes:number;capacity:number;booked_count:number;waitlist_count:number};
type MemberRow={id:string;full_name:string;email:string;phone:string;credits:number|null;plan:string|null;package_status:"Pending"|"Confirmed"|null;member_status:string|null;expiry_date:string|null};
type BookingRow={id:string;session_id:string;member_id:string;member_name:string;status:"booked"|"waitlisted";queue_number:number|null;attended_at:string|null};
type TaskRow={id:string;title:string;person_name:string;due_at:string;category:string;priority:string};
type StudioPack={id:string;name:string;description:string;credits:number;valid_days:number;active:boolean};
type Signal={id:string;kind:string;priority:"high"|"medium"|"low";title:string;reason:string;suggestedAction:string;personId?:string;sessionId?:string};
type ActionReply={items:Signal[];total:number;rules:string;today:{classes:number;bookings:number;waitlisted:number;capacity:number;occupancy:number};rescue:{total:number;trials:number;inactive:number;renewals:number;pendingPackages:number;openSeats:number}};

async function api<T>(path:string,method="GET",body?:unknown):Promise<T>{
 const response=await fetch(path,{method,credentials:"same-origin",cache:"no-store",headers:body===undefined?undefined:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});
 let data:Record<string,unknown>;try{data=await response.json() as Record<string,unknown>}catch{data={}}
 if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Operation failed ("+response.status+").");
 return data as T;
}
function classLabel(c:ClassRow,p:WorkspacePreferences){
 return c.title+" · "+new Date(c.starts_at).toLocaleString("en-GB",{timeZone:p.timezone,month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:p.timeFormat==="12h"});
}

export function StudioOperations({role,section,preferences}:{role:string;section:WorkspaceSection;preferences:WorkspacePreferences}){
 const owner=["owner","manager"].includes(role);
 const [classes,setClasses]=useState<ClassRow[]>([]),[members,setMembers]=useState<MemberRow[]>([]),[bookings,setBookings]=useState<BookingRow[]>([]);
 const [actions,setActions]=useState<Signal[]>([]),[today,setToday]=useState({classes:0,bookings:0,waitlisted:0,capacity:0,occupancy:0});
 const [rescue,setRescue]=useState({total:0,trials:0,inactive:0,renewals:0,pendingPackages:0,openSeats:0}),[tasks,setTasks]=useState<TaskRow[]>([]);
 const [selectedClass,setSelectedClass]=useState(""),[selectedMember,setSelectedMember]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [schedule,setSchedule]=useState({title:"Studio Class",instructor:"Instructor",room:preferences.defaultRoom,startsAt:"",durationMinutes:preferences.defaultClassDuration,capacity:preferences.defaultClassCapacity});
 const [packs,setPacks]=useState<StudioPack[]>([]),[packForm,setPackForm]=useState({name:"10 Class Pack",description:"",credits:10,validDays:60});
 const [repeat,setRepeat]=useState({enabled:false,until:"",weekdays:[1,3,5] as number[]});
 const [adjust,setAdjust]=useState({memberId:"",delta:5,reason:"Credit balance correction"}),[selectedPlan,setSelectedPlan]=useState<Record<string,string>>({});
 const [taskOutcomes,setTaskOutcomes]=useState<Record<string,string>>({});
 const [billing,setBilling]=useState<{subscription:{status:string;plan:string;enabled:boolean;periodEnd:string|null};checkoutConfigured:boolean}|null>(null);

 const refresh=useCallback(async()=>{
  const [c,m,a,t]=await Promise.all([
   api<{classes:ClassRow[]}>("/api/studio/classes"),api<{members:MemberRow[]}>("/api/studio/members"),
   api<ActionReply>("/api/studio/action-center"),api<{tasks:TaskRow[]}>("/api/studio/tasks")
  ]);
  setClasses(c.classes);setMembers(m.members);setActions(a.items);setToday(a.today);setRescue(a.rescue);setTasks(t.tasks);
  if(owner)void api<{packages:StudioPack[]}>("/api/studio/packages").then(x=>setPacks(x.packages)).catch(()=>{});
  if(owner)void api<{subscription:{status:string;plan:string;enabled:boolean;periodEnd:string|null};checkoutConfigured:boolean}>("/api/studio/subscription").then(setBilling).catch(()=>setBilling(null));
  setSelectedClass(old=>old||c.classes[0]?.id||"");setSelectedMember(old=>old||m.members[0]?.id||"");setAdjust(old=>({...old,memberId:old.memberId||m.members[0]?.id||""}));
 },[owner]);
 useEffect(()=>{void refresh().catch(e=>setMessage(e instanceof Error?e.message:"Could not load studio data."))},[refresh]);
 useEffect(()=>{setSchedule(prev=>({...prev,room:preferences.defaultRoom,durationMinutes:preferences.defaultClassDuration,capacity:preferences.defaultClassCapacity}))},[preferences.defaultRoom,preferences.defaultClassDuration,preferences.defaultClassCapacity]);
 useEffect(()=>{if(!selectedClass){setBookings([]);return}void api<{bookings:BookingRow[]}>("/api/studio/bookings?sessionId="+encodeURIComponent(selectedClass)).then(d=>setBookings(d.bookings)).catch(()=>setBookings([]))},[selectedClass]);

 async function perform(work:()=>Promise<string>){
  if(busy)return;setBusy(true);setMessage("");
  try{const info=await work();await refresh();if(selectedClass){const result=await api<{bookings:BookingRow[]}>("/api/studio/bookings?sessionId="+encodeURIComponent(selectedClass));setBookings(result.bookings)}setMessage(info)}
  catch(e){setMessage(e instanceof Error?e.message:"Request failed.")}finally{setBusy(false)}
 }
 function createSession(e:FormEvent<HTMLFormElement>){
  e.preventDefault();if(!schedule.startsAt){setMessage("Choose a class start time.");return}
  let isoStart:string;try{isoStart=localDateTimeToUTC(schedule.startsAt.slice(0,10),schedule.startsAt.slice(11,16),preferences.timezone)}catch(e){setMessage(e instanceof Error?e.message:"Invalid studio time.");return}
  void perform(async()=>{const detail={title:schedule.title,instructor:schedule.instructor,room:schedule.room,startsAt:isoStart,durationMinutes:schedule.durationMinutes,capacity:schedule.capacity};
   if(repeat.enabled){if(!repeat.until)throw Error("Select the last day of the series.");const result=await api<{classes:ClassRow[]}>("/api/studio/classes/series","POST",{...detail,startDate:schedule.startsAt.slice(0,10),endDate:repeat.until,time:schedule.startsAt.slice(11,16),weekdays:repeat.weekdays});return result.classes.length+" recurring "+preferences.classTerm.toLowerCase()+" created."}
   await api("/api/studio/classes","POST",detail);return preferences.classTerm.slice(0,-1)+" created in "+preferences.timezone+"."});
 }
 function book(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedClass||!selectedMember)return;void perform(async()=>{const result=await api<{booking:{status:string;alreadyExists:boolean}}>("/api/studio/bookings","POST",{sessionId:selectedClass,memberId:selectedMember});return result.booking.alreadyExists?"This "+preferences.memberTerm.slice(0,-1).toLowerCase()+" already has a booking/waitlist place.":result.booking.status==="waitlisted"?"Class full: added to waiting list; no "+preferences.creditTerm.toLowerCase()+" deducted.":"Booking confirmed; one "+preferences.creditTerm.slice(0,-1).toLowerCase()+" deducted if applicable."})}
 function cancel(b:BookingRow){if(!window.confirm("Cancel "+b.member_name+"'s "+b.status+" entry?"))return;void perform(async()=>{const x=await api<{booking:{promoted:{id:string}|null;alreadyCancelled:boolean}}>("/api/studio/bookings/"+b.id,"DELETE");return x.booking.alreadyCancelled?"Booking was already cancelled.":x.booking.promoted?"Cancelled and next eligible waitlisted member promoted.":"Booking cancelled."})}
 function markAttendance(b:BookingRow){if(b.attended_at){const reason=window.prompt("Why are you correcting this check-in? At least five characters.");if(!reason)return;void perform(async()=>{await api("/api/studio/bookings/"+b.id+"/attendance","DELETE",{reason});return "Check-in corrected and audited."})}else void perform(async()=>{await api("/api/studio/bookings/"+b.id+"/attendance","POST");return "Attendance recorded."})}
 function confirm(m:MemberRow){if(!owner)return;const packageId=selectedPlan[m.id]||packs[0]?.id,pack=packs.find(p=>p.id===packageId);if(!pack){setMessage("Create an internal class package first.");return}if(!window.confirm("Confirm "+pack.name+" for "+m.full_name+"? StudioTasker does not collect or verify member payment."))return;void perform(async()=>{await api("/api/studio/members/"+m.id+"/package","POST",{packageId:pack.id});return "Package entitlement confirmed by the studio."})}
 function adjustCredits(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!owner||!adjust.memberId)return;const m=members.find(x=>x.id===adjust.memberId);if(!m)return;if(!window.confirm((adjust.delta>0?"Add ":"Remove ")+Math.abs(adjust.delta)+" "+preferences.creditTerm.toLowerCase()+" "+(adjust.delta>0?"to ":"from ")+m.full_name+"?"))return;const requestKey=crypto.randomUUID();void perform(async()=>{const reply=await api<{adjustment:{credits:number}}>("/api/studio/members/"+m.id+"/credits","POST",{delta:adjust.delta,reason:adjust.reason,requestKey});return preferences.creditTerm+" now: "+reply.adjustment.credits+"."})}
 function addPack(e:FormEvent<HTMLFormElement>){e.preventDefault();void perform(async()=>{await api("/api/studio/packages","POST",packForm);return "Internal class package saved."})}
 function togglePack(p:StudioPack){void perform(async()=>{await api("/api/studio/packages/"+p.id,"PATCH",{active:!p.active});return p.active?"Package hidden from new assignments.":"Package available again."})}
 function startCheckout(plan:"monthly"|"annual"){if(!billing?.checkoutConfigured){setMessage("Checkout is not configured. No payment was started.");return}void perform(async()=>{const result=await api<{checkoutUrl:string}>("/api/studio/subscription","POST",{plan});window.location.assign(result.checkoutUrl);return "Opening secure StudioTasker subscription checkout."})}
 function todayAction(item:Signal,operation:"create_task"|"contacted"|"snooze"){void perform(async()=>{const result=await api<{notice:string}>("/api/studio/action-center/action","POST",{actionKey:item.id,operation});return result.notice})}
 function completeTask(t:TaskRow){const outcome=taskOutcomes[t.id]||"Contacted";if(!window.confirm("Mark this follow-up completed as '"+outcome+"'?"))return;void perform(async()=>{await api("/api/studio/tasks/"+t.id,"PATCH",{outcome});return "Follow-up outcome saved."})}

 return <div className="rd-ops" aria-label="Live studio operations">
  {message&&<div className="rd-feedback" role="status">{message}</div>}
  {section==="today"&&<section className="rd-today" aria-labelledby="studiotasker-today-title">
   <div className="rd-today-head"><div><p className="rd-eyebrow">YOUR DAILY OPERATING VIEW</p><h2 id="studiotasker-today-title">StudioTasker Today</h2><p>What deserves attention now — with a reason and a next action.</p></div><span>{actions.length} things to review</span></div>
   <div className="rd-today-stats"><div><small>{preferences.classTerm.toUpperCase()} TODAY</small><strong>{today.classes}</strong></div><div><small>BOOKINGS TODAY</small><strong>{today.bookings}</strong></div><div><small>OCCUPANCY</small><strong>{today.occupancy}%</strong><span>{today.bookings}/{today.capacity||0} places</span></div><div><small>WAITLISTED</small><strong>{today.waitlisted}</strong></div></div>
   <div className="rd-rescue"><div className="rd-rescue-title"><div><small>REVENUE RESCUE</small><h3>{rescue.total} opportunities to review</h3></div><p>Observed operational signals only.</p></div>
    <div className="rd-rescue-grid"><span><b>{rescue.trials}</b> trial follow-ups</span><span><b>{rescue.renewals}</b> renewals</span><span><b>{rescue.inactive}</b> inactive {preferences.memberTerm.toLowerCase()}</span><span><b>{rescue.pendingPackages}</b> package reviews</span><span><b>{rescue.openSeats}</b> underfilled {preferences.classTerm.toLowerCase()}</span></div></div>
   <div className="rd-action-list">{actions.length?actions.slice(0,18).map(item=><article key={item.id} className={"rd-action-item rd-action-"+item.kind}><div><span className={"rd-priority "+item.priority}>{item.priority}</span><strong>{item.title}</strong><p>{item.reason}</p><small>Suggested: {item.suggestedAction}</small></div><div className="rd-today-actions">{item.personId&&!item.id.startsWith("task:")&&<button disabled={busy} onClick={()=>todayAction(item,"contacted")}>Mark contacted</button>}{item.personId&&!item.id.startsWith("task:")&&<button disabled={busy} onClick={()=>todayAction(item,"create_task")}>Make task</button>}{item.sessionId&&<button onClick={()=>setSelectedClass(item.sessionId||"")}>Review class</button>}<button disabled={busy} onClick={()=>todayAction(item,"snooze")}>Tomorrow</button></div></article>):<p className="rd-empty">Nothing urgent from current studio data.</p>}</div>
   <p className="rd-tiny">Your rules: inactive after {preferences.inactiveDays} days · low {preferences.creditTerm.toLowerCase()} at {preferences.lowCreditsThreshold} · renewal window {preferences.renewalWindowDays} days · trial follow-up {preferences.trialFollowupHours}h · package review {preferences.packageReviewHours}h · open-seat signal at {preferences.openSeatsThreshold}+ places.</p>
  </section>}

  {section==="classes"&&<section className="rd-ops-section"><div className="rd-ops-section-title"><div><h3>{preferences.classTerm}</h3><p>Schedule, capacity, bookings, waitlist and attendance.</p></div><button type="button" disabled={busy} onClick={()=>void perform(async()=>"Latest class records loaded.")}>Refresh</button></div>
   {owner&&<details className="rd-ops-details"><summary>Create {preferences.classTerm.slice(0,-1).toLowerCase()}</summary><form className="rd-form" onSubmit={createSession}>
    <label>Name<input minLength={2} maxLength={100} required value={schedule.title} onChange={e=>setSchedule({...schedule,title:e.target.value})}/></label><label>Instructor<input minLength={2} maxLength={80} required value={schedule.instructor} onChange={e=>setSchedule({...schedule,instructor:e.target.value})}/></label><label>Room<input minLength={1} maxLength={80} required value={schedule.room} onChange={e=>setSchedule({...schedule,room:e.target.value})}/></label>
    <label>Starts in {preferences.timezone}<input type="datetime-local" required value={schedule.startsAt} onChange={e=>setSchedule({...schedule,startsAt:e.target.value})}/></label>
    <div className="rd-ops-pair"><label>Duration (minutes)<input type="number" min="15" max="240" required value={schedule.durationMinutes} onChange={e=>setSchedule({...schedule,durationMinutes:Number(e.target.value)})}/></label><label>Capacity<input type="number" min="1" max="100" required value={schedule.capacity} onChange={e=>setSchedule({...schedule,capacity:Number(e.target.value)})}/></label></div>
    <label className="rd-toggle"><input type="checkbox" checked={repeat.enabled} onChange={e=>setRepeat({...repeat,enabled:e.target.checked})}/> Repeat weekly</label>
    {repeat.enabled&&<div className="rd-repeat-config"><strong>Repeat on</strong><div className="rd-weekdays">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map((day,index)=><button type="button" aria-pressed={repeat.weekdays.includes(index)} className={repeat.weekdays.includes(index)?"selected":""} key={day} onClick={()=>setRepeat(v=>({...v,weekdays:v.weekdays.includes(index)?v.weekdays.filter(x=>x!==index):[...v.weekdays,index]}))}>{day}</button>)}</div><label>Repeat until<input type="date" min={schedule.startsAt.slice(0,10)} required value={repeat.until} onChange={e=>setRepeat({...repeat,until:e.target.value})}/></label></div>}
    <button className="rd-primary" disabled={busy}>{repeat.enabled?"Create weekly series":"Create"}</button></form></details>}
   <div className="rd-class-list">{classes.length?classes.slice(0,40).map(c=><button className={"rd-class-choice"+(selectedClass===c.id?" selected":"")} key={c.id} onClick={()=>setSelectedClass(c.id)}><strong>{classLabel(c,preferences)}</strong><small>{c.instructor} · {c.room} · {c.duration_minutes} min</small><span>{c.booked_count}/{c.capacity} booked · {c.waitlist_count} waiting</span></button>):<p className="rd-empty">No upcoming {preferences.classTerm.toLowerCase()}.</p>}</div>
   {classes.length>0&&<div className="rd-ops-subsection"><h4>Book or waitlist a {preferences.memberTerm.slice(0,-1).toLowerCase()}</h4><form className="rd-form" onSubmit={book}><label>{preferences.classTerm.slice(0,-1)}<select required value={selectedClass} onChange={e=>setSelectedClass(e.target.value)}>{classes.map(c=><option key={c.id} value={c.id}>{classLabel(c,preferences)}</option>)}</select></label><label>{preferences.memberTerm.slice(0,-1)}<select required value={selectedMember} onChange={e=>setSelectedMember(e.target.value)}><option value="">Select</option>{members.map(m=><option value={m.id} key={m.id}>{m.full_name} · {m.package_status||"Pending"} · {m.credits===null?"Unlimited":m.credits+" "+preferences.creditTerm.toLowerCase()}</option>)}</select></label><button className="rd-primary" disabled={busy||!selectedMember}>Book / join waitlist</button></form>
    <div className="rd-booking-list">{bookings.length?bookings.map(b=><div key={b.id}><span><b>{b.member_name}</b><small>{b.attended_at?"Checked in · ":""}{b.status}{b.status==="waitlisted"?" · #"+b.queue_number:""}</small></span><div className="rd-booking-actions">{b.status==="booked"&&<button disabled={busy} onClick={()=>markAttendance(b)}>{b.attended_at?"Correct check-in":"Check in"}</button>}<button disabled={busy||Boolean(b.attended_at)} onClick={()=>cancel(b)}>Cancel</button></div></div>):<p className="rd-empty">No active bookings in this class.</p>}</div></div>}
  </section>}

  {section==="members"&&owner&&<section className="rd-ops-section"><h3>{preferences.memberTerm} packages & {preferences.creditTerm.toLowerCase()}</h3><p className="rd-tiny">Studio-confirmed entitlement only; StudioTasker does not collect or verify member payment.</p>
   <div className="rd-pack-list">{members.length?members.map(m=><div key={m.id}><div><strong>{m.full_name}</strong><small>{m.package_status||"Pending"} · {m.plan||"No package"} · {m.credits===null?"Unlimited":m.credits+" "+preferences.creditTerm.toLowerCase()}</small></div>{m.package_status==="Pending"&&<div className="rd-pack-confirm"><label><span>Package</span><select value={selectedPlan[m.id]||packs[0]?.id||""} onChange={e=>setSelectedPlan(prev=>({...prev,[m.id]:e.target.value}))}>{packs.map(p=><option key={p.id} value={p.id}>{p.name} · {p.credits} {preferences.creditTerm.toLowerCase()} · {p.valid_days} days</option>)}</select></label><button disabled={busy} onClick={()=>confirm(m)}>Confirm package</button></div>}</div>):<p className="rd-empty">No {preferences.memberTerm.toLowerCase()} yet.</p>}</div>
   {members.some(m=>m.package_status==="Confirmed"&&m.credits!==null)&&<details className="rd-ops-details"><summary>Adjust {preferences.creditTerm.toLowerCase()} with an audit entry</summary><form className="rd-form" onSubmit={adjustCredits}><label>{preferences.memberTerm.slice(0,-1)}<select required value={adjust.memberId} onChange={e=>setAdjust({...adjust,memberId:e.target.value})}><option value="">Select</option>{members.filter(m=>m.package_status==="Confirmed"&&m.credits!==null).map(m=><option key={m.id} value={m.id}>{m.full_name} · {m.credits}</option>)}</select></label><label>{preferences.creditTerm} to add (+) or remove (−)<input type="number" required min="-1000" max="1000" value={adjust.delta} onChange={e=>setAdjust({...adjust,delta:Number(e.target.value)})}/></label><label>Reason<input required minLength={2} maxLength={200} value={adjust.reason} onChange={e=>setAdjust({...adjust,reason:e.target.value})}/></label><button className="rd-primary" disabled={busy||!adjust.memberId||adjust.delta===0}>Save audited adjustment</button></form></details>}
  </section>}

  {section==="followups"&&<section className="rd-ops-section"><h3>Open follow-ups</h3><div className="rd-followup-list">{tasks.length?tasks.slice(0,30).map(t=><div key={t.id}><div><strong>{t.title}</strong><small>{t.person_name} · {new Date(t.due_at).toLocaleDateString()} · {t.priority}</small></div><label>Outcome<select value={taskOutcomes[t.id]||"Contacted"} onChange={e=>setTaskOutcomes(prev=>({...prev,[t.id]:e.target.value}))}>{["Contacted","No answer","Reschedule","Converted","Completed"].map(x=><option key={x}>{x}</option>)}</select></label><button disabled={busy} onClick={()=>completeTask(t)}>Complete</button></div>):<p className="rd-empty">No open follow-up tasks.</p>}</div></section>}

  {section==="insights"&&<section className="rd-ops-section"><div className="rd-ops-section-title"><div><h3>Operational insights</h3><p>Small, explainable metrics built from the studio's own records.</p></div></div>
   <div className="rd-live-insights"><article><small>ACTIVE {preferences.memberTerm.toUpperCase()}</small><strong>{members.filter(m=>m.member_status==="Active").length}</strong></article><article><small>UPCOMING {preferences.classTerm.toUpperCase()}</small><strong>{classes.length}</strong></article><article><small>OPEN FOLLOW-UPS</small><strong>{tasks.length}</strong></article><article><small>TODAY OCCUPANCY</small><strong>{today.occupancy}%</strong></article><article><small>RESCUE SIGNALS</small><strong>{rescue.total}</strong></article></div>
  </section>}

  {section==="settings"&&<>{owner&&<section className="rd-ops-section"><div className="rd-ops-section-title"><div><h3>StudioTasker subscription</h3><p>Your SaaS subscription; member money stays outside StudioTasker.</p></div></div><p><strong>{billing?.subscription.plan||"No plan"} · {billing?.subscription.status||"Inactive"}</strong>{billing?.subscription.periodEnd&&" · Through "+new Date(billing.subscription.periodEnd).toLocaleDateString()}</p>{billing?.checkoutConfigured?<div className="rd-contact-actions"><button disabled={busy} onClick={()=>startCheckout("monthly")}>Choose monthly</button><button disabled={busy} onClick={()=>startCheckout("annual")}>Choose annual</button></div>:<p className="rd-tiny">Subscription checkout is not configured in this environment.</p>}</section>}
   {owner&&<section className="rd-ops-section"><div className="rd-ops-section-title"><div><h3>Internal class packages</h3><p>Define {preferences.creditTerm.toLowerCase()} and validity for operational tracking.</p></div></div><details className="rd-ops-details"><summary>Create package</summary><form className="rd-form" onSubmit={addPack}><label>Name<input required minLength={2} maxLength={70} value={packForm.name} onChange={e=>setPackForm({...packForm,name:e.target.value})}/></label><label>Description<input maxLength={240} value={packForm.description} onChange={e=>setPackForm({...packForm,description:e.target.value})}/></label><div className="rd-ops-pair"><label>{preferences.creditTerm}<input type="number" min="1" max="100" required value={packForm.credits} onChange={e=>setPackForm({...packForm,credits:Number(e.target.value)})}/></label><label>Validity (days)<input type="number" min="7" max="365" required value={packForm.validDays} onChange={e=>setPackForm({...packForm,validDays:Number(e.target.value)})}/></label></div><button className="rd-primary" disabled={busy}>Save package template</button></form></details><div className="rd-pack-list">{packs.length?packs.map(p=><div key={p.id}><div><strong>{p.name}</strong><small>{p.credits} {preferences.creditTerm.toLowerCase()} · {p.valid_days} days · {p.active?"Available":"Hidden"}</small></div><button disabled={busy} onClick={()=>togglePack(p)}>{p.active?"Hide":"Restore"}</button></div>):<p className="rd-empty">No internal packages yet.</p>}</div></section>}
  </>}
 </div>;
}
